# Generated by Django 5.0.2 on 2024-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.CharField(default='no message', max_length=100),
        ),
    ]
