# Generated by Django 5.0.2 on 2024-05-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='nickname',
        ),
    ]
