# Generated by Django 5.0.2 on 2024-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
