# Generated by Django 5.0.2 on 2024-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
