# Generated by Django 5.0.2 on 2024-05-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourmanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('players', models.JSONField(default=list)),
                ('rounds', models.IntegerField(default=1)),
                ('player_count', models.CharField(choices=[('4', 'Four'), ('8', 'Eight')], default='4', max_length=1)),
                ('current_round', models.IntegerField(default=1)),
                ('finnished', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=20, null=True)),
                ('player2', models.CharField(blank=True, max_length=20, null=True)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('round', models.IntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tourmanent')),
            ],
        ),
    ]
