# Generated by Django 5.0.7 on 2024-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('players', models.JSONField(default=list)),
                ('rounds', models.IntegerField(default=1)),
                ('player_count', models.CharField(choices=[('4', 'Four'), ('8', 'Eight')], default='4', max_length=1)),
                ('current_round', models.IntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=20, null=True)),
                ('player2', models.CharField(blank=True, max_length=20, null=True)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('round', models.IntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
