# Generated by Django 5.0.2 on 2024-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmanent',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
