# Generated by Django 5.0.7 on 2024-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_rename_finnished_tourmanent_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
