# Generated by Django 5.0.7 on 2024-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournamentmatch_score1_tournamentmatch_score2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
