# Generated by Django 5.0.2 on 2024-05-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
