# Generated by Django 5.0.2 on 2024-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_match_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_pauses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_pauses',
            field=models.IntegerField(default=0),
        ),
    ]
