# Generated by Django 4.2.10 on 2024-03-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_online_alter_friendrequest_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_from_42',
            field=models.BooleanField(default=False),
        ),
    ]
