# Generated by Django 4.2.10 on 2024-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_from_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_ferch_from_intra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username_ferch_from_intra',
            field=models.BooleanField(default=True),
        ),
    ]
