# Generated by Django 4.2.10 on 2024-03-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_blockedlist_blocked_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='first_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
