# Generated by Django 5.0.3 on 2024-03-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_first_email_user_first_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_ferch_from_intra',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_ferch_from_intra',
        ),
    ]
