# Generated by Django 5.0.2 on 2024-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_email_ferch_from_intra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
    ]
