# Generated by Django 4.2.14 on 2024-07-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_elo_user_games_lost_user_games_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
